# Generated by Django 2.1.5 on 2019-04-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190305_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
