# Generated by Django 2.1.5 on 2019-02-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190224_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='type',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='urgency',
            name='type',
            field=models.CharField(max_length=80),
        ),
    ]
