# Generated by Django 2.1.5 on 2019-03-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190302_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
